# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-17 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(default='Nombre', error_messages={'unique': 'Este titulo no es unico, intenta de nuevo'}, help_text='Debe ser un titulo unico', max_length=120, unique=True, verbose_name='Post')),
            ],
        ),
    ]
