# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-17 09:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20180217_0855'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='publish_date',
            new_name='created',
        ),
    ]
