# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-17 09:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_auto_20180217_0903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='genre',
        ),
    ]
